apiVersion: v1
kind: Service
metadata:
  name: argocd-app-service
spec:
  selector:
    app: argocd-app # Selects Pods with this label
  ports:
    - protocol: TCP
      port: 80 # Port exposed by the Service
      targetPort: 80 # Port on the Pods to forward traffic to
  type: LoadBalancer # Or ClusterIP, NodePort depending on your needs
